// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NuspecGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNuspecGeneratorPackageString = "1a6861a1-ce0b-40bc-8c9c-dd4a2bbb509a";
        public static Guid guidNuspecGeneratorPackage = new Guid(guidNuspecGeneratorPackageString);

        public const string guidNuspecGeneratorPackageCmdSetString = "21c3ed1d-dcfb-4145-ab59-1db105d28c68";
        public static Guid guidNuspecGeneratorPackageCmdSet = new Guid(guidNuspecGeneratorPackageCmdSetString);

        public const string guidImagesString = "24686238-2cd1-4396-99e4-6e0ffa63caee";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NuspecGeneratorGroup = 0x1020;
        public const int CommandId = 0x0100;
        public const int bmpPic = 0x0001;
    }
}