// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NuspecGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "bb82e765-ab80-4b8b-a93c-3aa7399ee392";
        public const string Name = "Nuspec Generator";
        public const string Description = @"Provides the ability to generate nuspec files including dependencies for Non-SDK-style .NET Framework projects with Package References";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Afaq Khan";
        public const string Tags = "nuget, nuspec, generate, update, dependencies, package, references";
    }
}
